---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest

---

apiVersion: v1
kind: Service
metadata:
  name: utrains-service
spec:
  selector:
    app: nginx
  type: LoadBalancer   
  ports:
  - name: utrains-service-port
    protocol: TCP
    port: 80
    targetPort: 80

